parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     rent
    database_user:     root
    database_password: mysql

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            de_DE
    secret:            3d5520672f7869636d53286853

    blocking_period:   2