jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        IMAG\LdapBundle\User\LdapUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: testme, roles: [ 'ROLE_USER' ] }
                    admin: { password: testme, roles: [ 'ROLE_ADMIN' ] }
        ldap:
            id: imag_ldap.security.user.provider
        multiple:
            chain:
                providers: [ldap, in_memory]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: true
            provider: multiple
            form_login:
                login_path: index
                check_path: login_check
                remember_me: true
                use_referer: true
                failure_path: login
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            imag_ldap:
                login_path:   index
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

imag_ldap:
    client:
        host: %ldap_host%
        port: %ldap_port%
        version: %ldap_version%
        username: %ldap_admin_user%
        password: %ldap_admin_pass%
        referrals_enabled: false
        bind_username_before: false
        skip_roles: true

    user:
        base_dn: %ldap_user_basedn%
        name_attribute: uid
        attributes: [sn, givenname, mail, mlupersontype]
