<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130419120353 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Booking (id INT AUTO_INCREMENT NOT NULL, device_id INT DEFAULT NULL, user_id INT DEFAULT NULL, `from` DATE NOT NULL, `to` DATE NOT NULL, updated DATETIME DEFAULT NULL, created DATETIME NOT NULL, INDEX IDX_2FB1D44294A4C7D4 (device_id), INDEX IDX_2FB1D442A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, updated DATETIME DEFAULT NULL, created DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE category_device (category_id INT NOT NULL, device_id INT NOT NULL, INDEX IDX_6C77CF512469DE2 (category_id), INDEX IDX_6C77CF594A4C7D4 (device_id), PRIMARY KEY(category_id, device_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Device (id INT AUTO_INCREMENT NOT NULL, serialNumber VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, updated DATETIME DEFAULT NULL, created DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE User (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, commonName VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, admin TINYINT(1) NOT NULL, updated DATETIME DEFAULT NULL, created DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D44294A4C7D4 FOREIGN KEY (device_id) REFERENCES Device (id)");
        $this->addSql("ALTER TABLE Booking ADD CONSTRAINT FK_2FB1D442A76ED395 FOREIGN KEY (user_id) REFERENCES User (id)");
        $this->addSql("ALTER TABLE category_device ADD CONSTRAINT FK_6C77CF512469DE2 FOREIGN KEY (category_id) REFERENCES Category (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE category_device ADD CONSTRAINT FK_6C77CF594A4C7D4 FOREIGN KEY (device_id) REFERENCES Device (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE category_device DROP FOREIGN KEY FK_6C77CF512469DE2");
        $this->addSql("ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D44294A4C7D4");
        $this->addSql("ALTER TABLE category_device DROP FOREIGN KEY FK_6C77CF594A4C7D4");
        $this->addSql("ALTER TABLE Booking DROP FOREIGN KEY FK_2FB1D442A76ED395");
        $this->addSql("DROP TABLE Booking");
        $this->addSql("DROP TABLE Category");
        $this->addSql("DROP TABLE category_device");
        $this->addSql("DROP TABLE Device");
        $this->addSql("DROP TABLE User");
    }
}
