services:
    # Menu builder
    rent.menu_builder:
        class: UniHalle\RentBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.context"]

    # Admin Navbar
    rent.menu:
        class: Knp\Menu\MenuItem
        factory_service: rent.menu_builder
        factory_method: createMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: menu }

    rent.right_menu:
        class: Knp\Menu\MenuItem
        factory_service: rent.menu_builder
        factory_method: createRightMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: right_menu }

    rent.navbar:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            - { leftmenu: @rent.menu=, rightmenu: @rent.right_menu= }
            - {  }
            - { title: "Geräteverleih", titleRoute: "index", staticTop: true, isFluid: false, inverse: false, template:RentBundle:Menu:navbar.html.twig }
        tags:
            - { name: mopa_bootstrap.navbar, alias: navbar }

    UniHalle.twig.ceil_extension:
        class: UniHalle\RentBundle\Twig\CeilExtension
        tags:
            - { name: twig.extension }
